from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name="home"),
    path('register', views.register, name="register"),
    path('register/<str:role>/', views.register, name="register_role"),
    path('login', views.login_page, name="login"),
    path('logout', views.logout_page, name="logout"),
    path('seller/dashboard/', views.seller_dashboard, name='seller_dashboard'),
    path('seller/products/', views.seller_products, name='seller_products'),
    path('seller/add-product/', views.seller_add_product, name='seller_add_product'),
    path('seller/api/smart-price/', views.get_smart_price, name='get_smart_price'),
    path('seller/products/edit/<int:product_id>/', views.seller_edit_product, name='seller_edit_product'),
    path('seller/products/delete/<int:product_id>/', views.seller_delete_product, name='seller_delete_product'),
    path('seller/orders/', views.seller_orders, name='seller_orders'),
    path('seller/orders/confirm/<int:order_id>/', views.seller_confirm_order, name='seller_confirm_order'),
    path('seller/orders/ship/<int:order_id>/', views.seller_ship_order, name='seller_ship_order'),
    path('seller/earnings/', views.seller_earnings, name='seller_earnings'),
    path('seller/low-stock/', views.seller_low_stock, name='seller_low_stock'),
    path('seller/low-stock/restock/<int:product_id>/', views.seller_restock_product, name='seller_restock_product'),
    path('admin/', views.admin_dashboard, name='admin_dashboard'),
    path('admin/vendor-approvals/', views.admin_vendor_approvals, name='admin_vendor_approvals'),
    path('admin/vendor-action/<int:seller_id>/', views.admin_vendor_action, name='admin_vendor_action'),
    path('admin/categories/', views.admin_categories, name='admin_categories'),
    path('admin/orders/', views.admin_all_orders, name='admin_all_orders'),
    path('admin/commission-settings/', views.admin_commission_settings, name='admin_commission_settings'),
    path('admin/refund-requests/', views.admin_refund_requests, name='admin_refund_requests'),
    path('admin/analytics/', views.admin_analytics, name='admin_analytics'),
    path('payment/verify/', views.payment_verify, name='payment_verify'),
    path('cart/', views.cart_page, name="cart_page"),
    path('remove_cart/<str:cid>/', views.remove_page, name="remove_cart"),
    path('remove_fav/<str:fid>/', views.remove_fav, name="remove_fav"),
    path('fav/', views.fav_page, name="fav"),
    path('favviewpage/', views.favviewpage, name="favviewpage"),
    path('addtocart/', views.add_to_cart, name="addtocart"),
    path('collections', views.collections, name="collections"),
    path('collections/<str:name>', views.collectionsview, name="collections"),
    path('collections/<str:cname>/<str:pname>/', views.product_details, name='product_details'),
    path('checkout/', views.checkout, name='checkout'),
    path('orders/', views.orders_page, name='orders'),
    path('profile/', views.profile_view, name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),
    path('profile/add-address/', views.add_address, name='add_address'),
    path('profile/create/', views.create_profile, name='create_profile'),
]

